### ISSUE TITLE
Build Test failed on centos with GeForce GTX TITAN  on 'NVIDIA CUDA'

### ISSUE THREAD

**Issue by lewisKit** [kif/sift_pyocl#7]
Hi I want to build the package on the centos server, but I have problem when trying to building and getting it to work.

I run the command 

```shell
$ python setup.py build
```
and I get the following info:

```
UserWarning: Unknown distribution option: 'test_suite'
 warnings.warn(msg)
running build
running build_py
['openCL/keypoints_cpu.cl', 'openCL/matching_gpu.cl', 'openCL/keypoints_gpu1.cl', 'openCL/matching_cpu.cl', 'openCL/keypoints_gpu2.cl', 'openCL/orientation_cpu.cl', 'openCL/preprocess.cl', 'openCL/image.cl', 'openCL/orientation_gpu.cl', 'openCL/memset.cl', 'openCL/gaussian.cl', 'openCL/convolution.cl', 'openCL/algebra.cl', 'openCL/reductions.cl', 'openCL/transform.cl']
```

It seems to be good. And then I ran the test command. And I get the following error:

```
  warnings.warn(msg)
running build
running build_py
running test
Traceback (most recent call last):
  File "test_all.py", line 47, in <module>
    from test_gaussian import test_suite_gaussian
  File "/mnt/hd1/home/fengyihao/sift_pyocl/test/test_gaussian.py", line 67, in <module>
    program = pyopencl.Program(ctx, kernel_src).build("-D WORKGROUP=%s" % kernels[kernel])
  File "/mnt/hd1/home/fengyihao/anaconda2/envs/cluster/lib/python2.7/site-packages/pyopencl-2016.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 474, in build
    options_bytes=options_bytes, source=self._source)
  File "/mnt/hd1/home/fengyihao/anaconda2/envs/cluster/lib/python2.7/site-packages/pyopencl-2016.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 509, in _build_and_catch_errors
    raise err
pyopencl.cffi_cl.RuntimeError: clbuildprogram failed: BUILD_PROGRAM_FAILURE -

Build on <pyopencl.Device 'GeForce GTX TITAN' on 'NVIDIA CUDA' at 0x2a545f0>:

<kernel>:45:18: error: variadic macros not supported in OpenCL
  #define printf(...)
                 ^
<kernel>:207:61: warning: unknown attribute 'max_constant_size' ignored
            __constant        float * min_in __attribute__((max_constant_size(MAX_CONST_SIZE))),
                                                            ^
<kernel>:208:61: warning: unknown attribute 'max_constant_size' ignored
            __constant        float * max_in __attribute__((max_constant_size(MAX_CONST_SIZE))),
                                                            ^
<kernel>:209:62: warning: unknown attribute 'max_constant_size' ignored
            __constant        float * max_out __attribute__((max_constant_size(MAX_CONST_SIZE))),
                                                             ^

```

Before this, I think there is a bug that the code generates the directory names 'lib', but in the 'utilstest.py' file, it seems you write the code:

```Python
architecture = "lib" %(platform,sys.version_info[0], sys.version_info[1])

```

so the code cannot detect the directory. Then I changed your code in 'utilstest.py' to match the name in the build.

And then I get the error above mentioned. 

I think I have successfully built the package pyopencl with gpu support.

By the way, I built all these in an anaconda environment.

Thanks.

**Comment by kif** [comment]
Hi,

I just tested the installation procedure and it works under debian8 and an older version of pyopencl 2014.1-3.
The Titan is not a pb: I tested the code under Fermi, Kepler & Maxwell generation without pb.
Which version of your code are you using ?

> <kernel>:45:18: error: variadic macros not supported in OpenCL
>   #define printf(...)

Funny: there is no printf used in our code.

> 
> 
> Before this, I think there is a bug that the code generates the directory names 'lib', but in the 'utilstest.py' file, it seems you write the code:
> 
> ```Python
> architecture = "lib" %(platform,sys.version_info[0], sys.version_info[1])
> 
> ```

This is a trick to do a pseudo-install and use it to perform the tests. 

> 
> I think I have successfully built the package pyopencl with gpu support.
> 
> By the way, I built all these in an anaconda environment.
> 

I have limited knowledge with anaconda so I cannot tell you if it is related or not.

Which driver version are you using ?

Can you run any pyopencl program ?

Cheers,

Jerome

**Comment by lewisKit** [comment]
Hi Jerome,

I install the pyopencl with a version of 2016-01. I am not sure whether the problem is with the version.

I would reinstall the version of 2014 and check it later.

Thanks,
Lewis

**Comment by lewisKit** [comment]
Hi Jerome,

I changed the pyopencl version to 2014.1 and scipy version to 0.16.1, and finally all test case has passed!

By the way, is there any plan to update the version of dependencies? Since it is quite difficult to find a pyopencl version of 2014.1.

Best,
Lewis

**Comment by kif** [comment]
On Tue, 14 Jun 2016 11:47:49 -0700
lewiskit <notifications@github.com> wrote:

> Hi Jerome,
> 
> I changed the pyopencl version to 2014.1 and scipy version to 0.16.1, and finally all test case has passed!
> 
> By the way, is there any plan to update the version of dependencies? Since it is quite difficult to find a pyopencl version of 2014.1.

It is likely this code will be merged into the silx-kit later this year but it is not our highest priority.

Cheers,
